const sampleListings = [
    {
      title: "Cozy Beachfront Cottage",
      description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
      image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
      price: 1500,
      location: "Malibu",
      country: "United States",
    },
    {
      title: "Modern Loft in Downtown",
      description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
      image: "https://a0.muscache.com/im/pictures/798984ba-fef5-46c1-aa07-137d2d2998e9.jpg?im_w=1440&im_q=highq",
      price: 1200,
      location: "New York City",
      country: "United States",
    },
    {
      title: "Mountain Retreat",
      description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
      image: "https://a0.muscache.com/im/pictures/miso/Hosting-832403672453803433/original/bc77fa96-6e28-4d7e-947b-4ba5160777d8.jpeg?im_w=1440&im_q=highq",
      price: 1000,
      location: "Aspen",
      country: "United States",
    },
    {
      title: "Historic Villa in Tuscany",
      description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
      image: "",
      price: 2500,
      location: "Florence",
      country: "Italy",
    },
    {
      title: "Secluded Treehouse Getaway",
      description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
      image: "https://a0.muscache.com/im/pictures/0c7865ec-d2f0-4fd1-8e29-3613d0a86724.jpg?im_w=1440&im_q=highq",
      price: 800,
      location: "Portland",
      country: "United States",
    },
    {
      title: "Beachfront Paradise",
      description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
      image: "https://a0.muscache.com/im/pictures/a84d991e-8d4a-4ff6-818b-ca07292d3343.jpg?im_w=1440&im_q=highq",
      price: 2000,
      location: "Cancun",
      country: "Mexico",
    },
    {
      title: "Rustic Cabin by the Lake",
      description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
      image: "https://a0.muscache.com/im/pictures/108c1e02-aa40-40e4-aa14-c7bb52dacdbc.jpg?im_w=1440&im_q=highq",
      price: 900,
      location: "Lake Tahoe",
      country: "United States",
    },
    {
      title: "Luxury Penthouse with City Views",
      description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
      image: "",
      price: 3500,
      location: "Los Angeles",
      country: "United States",
    },
    {
      title: "Ski-In/Ski-Out Chalet",
      description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
      image: "https://a0.muscache.com/im/pictures/miso/Hosting-832403672453803433/original/bc77fa96-6e28-4d7e-947b-4ba5160777d8.jpeg?im_w=1440&im_q=highq",
      price: 3000,
      location: "Verbier",
      country: "Switzerland",
    },
    {
      title: "Safari Lodge in the Serengeti",
      description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
      image: "https://a0.muscache.com/im/pictures/hosting/Hosting-1126839634398201811/original/53511e53-aa22-43e0-b5f6-c2e38a98f30e.jpeg?im_w=1440&im_q=highq",
      price: 4000,
      location: "Serengeti National Park",
      country: "Tanzania",
    },
    {
      title: "Historic Canal House",
      description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
      image: "https://a0.muscache.com/im/pictures/miso/Hosting-832403672453803433/original/bc77fa96-6e28-4d7e-947b-4ba5160777d8.jpeg?im_w=1440&im_q=highq",
      price: 1800,
      location: "Amsterdam",
      country: "Netherlands",
    },
    {
      title: "Private Island Retreat",
      description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
      image: "https://a0.muscache.com/im/pictures/miso/Hosting-997426152002576278/original/99ccd193-8c7f-429e-9e79-f973897e1313.jpeg?im_w=1440&im_q=highq",
      price: 10000,
      location: "Fiji",
      country: "Fiji",
    },
    // Add similar entries here up to 30 listings
  ];
  
  module.exports = { data: sampleListings };
  